FROM python:3.11-slim

RUN apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /www/main
COPY requirements/ocr.txt .
COPY templates/ocr.html templates/ocr.html
RUN pip install --no-cache-dir -r ocr.txt
COPY ocr.py .

EXPOSE 5002
CMD ["python", "ocr.py"]