FROM python:3.11-slim

RUN apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /www/main
COPY requirements/api.txt .
COPY templates/api templates/api
RUN pip install --no-cache-dir -r api.txt
COPY api.py .

EXPOSE 5000
CMD ["python", "api.py"]