FROM python:3.11-slim

RUN apt-get update && apt-get upgrade -y && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /www/main
COPY requirements/meta_extract.txt .
COPY templates/meta_extract.html templates/meta_extract.html
RUN pip install --no-cache-dir -r meta_extract.txt
COPY meta_extract_flask.py .

EXPOSE 5001
CMD ["python", "meta_extract_flask.py"]