# DopplerSecret PERTAMA — Sinkronisasi ENV Aplikasi
# Memindahkan SEMUA variabel aplikasi ke k8s secret 'akarstack-app-env'
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: akarstack-doppler-app
  namespace: akarstack
spec:
  tokenSecret:
    name: doppler-app-token-secret
  managedSecret:
    name: akarstack-app-env
    namespace: akarstack

---

# DopplerSecret KEDUA — Auto-sync ke secret yang dibutuhkan CNPG
# Ini menggantikan cara manual buat secret 'akarstack-pg-app-credentials'
# Sekarang semuanya otomatis terkelola dari dashboard Doppler kamu.
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: akarstack-doppler-pg-app-creds
  namespace: akarstack
spec:
  tokenSecret:
    name: doppler-app-token-secret
  managedSecret:
    name: akarstack-pg-app-credentials
    namespace: akarstack
  processors:
    DB_USER:
      type: plain
      asName: username
    DB_PASSWORD:
      type: plain
      asName: password