; Fill in IPs from `terraform output public_ips` after `terraform apply`
[k3s_server]
k3s-server ansible_host=<IP_PUBLIC_CONTROL_PLANE> ansible_user=uniska

[k3s_workers]
worker-1 ansible_host=<IP_PRIVATE_WORKER_1> ansible_user=uniska
worker-2 ansible_host=<IP_PRIVATE_WORKER_2> ansible_user=uniska

[k3s_cluster:children]
k3s_server
k3s_workers


# Before: ansible_ssh_common_args='-o ProxyJump=uniska@<IP_PUBLIC_CONTROL_PLANE> -o StrictHostKeyChecking=no'
[k3s_workers:vars]
# After: Nambah forwardagent biar bisa masuk ssh
ansible_ssh_common_args='-o ProxyJump=uniska@<IP_PUBLIC_CONTROL_PLANE> -o ForwardAgent=yes -o StrictHostKeyChecking=no'
#ansible_ssh_common_args='-o ProxyJump=uniska@<IP_PUBLIC_CONTROL_PLANE>:2234 -o ForwardAgent=yes -o StrictHostKeyChecking=no'

[k3s_cluster:vars]
ansible_port=22
#ansible_port=2234
ansible_ssh_private_key_file=~/.ssh/id_rsa_azure
ansible_python_interpreter=/usr/bin/python3